### ISSUE TITLE
Please connect Metamask to Localhost:8545

### ISSUE THREAD

**Issue by yaroslavdubinskiy** [NomicFoundation/hardhat-boilerplate#54]
I can't connect to Localhost:8545 by changing the chainID.

**Comment by gg-martins091** [comment]
I also couldn't understand how to get the network to run locally, it would be great if it was added to some sort of docs as the tutorial page doesn't dive into the frontend part of this repo.

For now, if you are using Metamask on ropsten, change `HARDHAT_NETWORK_ID` to "3".
