### ISSUE TITLE
when run npx  hardhat node 

### ISSUE THREAD

**Issue by githublister** [NomicFoundation/hardhat-boilerplate#69]
You are using a version of Node.js that is not supported by Hardhat, and it may work incorrectly, or not work at all.

Please, make sure you are using a supported version of Node.js.

To learn more about which versions of Node.js are supported go to https://hardhat.org/nodejs-versions
Error HH604: Error running JSON-RPC server: error:0308010C:digital envelope routines::unsupported

For more info go to https://hardhat.org/HH604 or run Hardhat with --show-stack-traces

**Comment by sylwesterdigital** [comment]
The same. The boiler-plate is outdated. They recommend to install node v.18 but this boilerplate works with 16.17. Use ``nvm`` to change to node version.

**Comment by fvictorio** [comment]
Thank you for letting us know. I'm gonna update the version of hardhat used. In the meantime, you can just do `npm i --save-dev hardhat@latest`
