### ISSUE TITLE
Is this really recommended project structure? 

### ISSUE THREAD

**Issue by D1scoDancer** [NomicFoundation/hardhat-boilerplate#78]
I see that there may be a problem with nested node_modules. Would you really recommend building projects like that?

**Comment by fvictorio** [comment]
> I see that there may be a problem with nested node_modules

What do you mean?

**Comment by alcuadrado** [comment]
There are many approaches to do it, you can also use a monorepo. We used this here to keep it simple, as this repository is used in the tutorial.

I'm personally ok with not using a monorepo, and have used nested_node modules with success tons of time. We even have a monorepo and a nested node_module in the hardhat repo. Now, it may require a lot of discipline or proper setup linter, as you can access uninstalled dependencies, but that's the norm in node.

**Comment by D1scoDancer** [comment]
Thank you for this answer. That is advice that I was looking for.
