### ISSUE TITLE
to.be.reverted to not work as expected in your example

### ISSUE THREAD

**Issue by InfectedIsm** [NomicFoundation/hardhat-boilerplate#79]
Hi, I've used your boilerplate for a personal project, but I found out that VM revert are not caught correctly.

Reproduce steps :
https://github.com/NomicFoundation/hardhat-boilerplate/blob/13bd712c1285b2de572f14d20e6a750ae08565c0/test/Token.js#L101-L103

Remove to.be.revertedWith :
```
      await expect(
        hardhatToken.connect(addr1).transfer(owner.address, 1)
      );
```

Test still passes :
      ✔ Should fail if sender doesn't have enough tokens

Any idea why ?  I found your boilerplate code really useful, too bad I cannot use it

Thanks

**Comment by fvictorio** [comment]
If you do `await expect(...something...)`, the promise returned inside the `expect` will be captured by Chai. If you then don't assert anything on that promise, then the result will be discarded and the test pass.

To check that the transaction indeed fails, remove the `expect` too:

```js
await hardhatToken.connect(addr1).transfer(owner.address, 1)
```

**Comment by InfectedIsm** [comment]
Thanks a lot for taking time to answer ! I had misunderstood its behavior
