### ISSUE TITLE
Error: invalid address or ENS name

### ISSUE THREAD

**Issue by micahalcorn** [NomicFoundation/hardhat-boilerplate#83]
If you neglect to run `npx hardhat run scripts/deploy.js --network localhost` before starting the frontend and connecting a wallet, you will get an endless spinner and this error in the console. However, I'm still getting the error after deploying the contract. It's not a blocker though because the transfer form now loads.

<img width="960" alt="Screen Shot 2023-01-08 at 8 52 49 AM" src="https://user-images.githubusercontent.com/273937/211208878-4076cc28-e22c-4e16-8f7b-683bc69d4157.png">

**Comment by alcuadrado** [comment]
You are passing ethers an value were it expects an address.

This issue as is it's not actionable, so I'm closing it. Feel free to hop by our discord for help :)
